Remove zaza utils
canonical/charmed-openstack-upgrader pull request #10
Opened 2023-06-21 14:58 UTC by esunar

Removed all zaza_utils we have single file for all juju interaction.
Every juju operation works in async
utils/**  package unit tests not yet included
utils/**  package type checking ignored

2023-06-22 15:25 UTC, rgildein approved these changes
LGTM,
These are huge change, so hopefully a check it properly.

2023-06-22 20:38 UTC, esunar commented on pyproject.toml
> +omit = ["tests/**", "docs/**", "lib/**", "snap/**", "build/**", "setup.py", "cou/utils/**"]
I am adding add the moment

2023-06-22 21:11 UTC, gabrielcocenza reviewed
If I understand correctly, we are moving to async but we are still using code that comes from zaza. I think it worth mention that in the code to be easier to track if some change happens in the functions that we are going to use.

2023-06-27 20:26 UTC, gabrielcocenza requested changes
Left some points to be addressed.

I think this change is too big to also include the analyze part. I think we should split this PR with the changes from sync to async and then add the analyze part.

2023-06-29 09:03 UTC, esunar commented on cou/utils/juju_utils.py
> +def extract_charm_name(charm: str) -> str:
ok

2023-06-29 09:03 UTC, esunar commented on cou/exceptions.py
> +class InvalidCharmNameError(Exception):
ok

2023-06-29 09:12 UTC, esunar commented on cou/__main__.py
> +jasyncio.run(cli.entrypoint())
ok

2023-06-29 09:14 UTC, esunar commented on cou/steps/plan.py
>      logging.info(args)  # for placeholder
As commented it is just for placeholder(for avoiding unused variable warning). When you create actual implementation it will be removed.

2023-06-29 09:16 UTC, esunar commented
> Left some points to be addressed.
> 
> I think this change is too big to also include the analyze part. I think we should split this PR with the changes from sync to async and then add the analyze part.

Yes it is a big change however analyze part is a single file addition, this will not make it easier to review if we separate it to a new mr.

2023-06-29 13:01 UTC, gabrielcocenza approved these changes
LGTM.

2023-06-29 18:39 UTC, gabrielcocenza commented
These changes are now included at #12 with the removal of zaza_utils, turn the interaction with juju async and the analyze module.

2023-06-29 18:39 UTC, closed without merging