introduce cancel to `UpgradeStep`
canonical/charmed-openstack-upgrader pull request #114
Opened 2023-10-16 20:03 UTC by rgildein

Introduce cancel to `UpgradeStep`, which will cancel all sub-steps. The `cancel` can by run with `safe=True` (default value), which will keep all pending task running and prevent new one to be triggered. The `safe=False` will cancel also all pending `asyncio.Task` (running), which can cause stopping in middle of step and break cloud.

With these changes I also used coroutine as input of `UpgradeStep` instead of function and parameters. This helps with catching calling some coroutine with wrong arguments, e.k. linting cat catch it. However this change required to add warning ignore, since coroutines can be un-awaited in case of only planning.

FYI: We could not define `UpgradeStep` as `asyncio.Task` , since `asyncio.Task` is scheduled to be run as soon as possible if it's run in loop already. We can use it only if whole planning will be not asynchronous. 

related: #103 (preparation for proper handling of `KeyboardInterrupt`

2023-10-18 15:01 UTC, gabrielcocenza commented on tests/unit/steps/test_steps.py
> +def test_step_cancel():
```suggestion
def test_step_cancel_safe():
```

2023-10-18 15:02 UTC, gabrielcocenza commented on tests/unit/steps/test_steps.py
> +def test_step_unsafe_cancel():
```suggestion
def test_step_cancel_unsafe():
```

2023-10-18 15:09 UTC, gabrielcocenza commented on tests/unit/steps/test_steps.py
> +    # warnings.filterwarnings("ignore", message="coroutine '.*' was never awaited")
is this comment missing to remove?

2023-10-18 17:36 UTC, rgildein commented on tests/unit/steps/test_steps.py
> +    # coro = mock_coro(*args)
Thanks, I was debugging the warning errors.

2023-10-18 17:37 UTC, rgildein commented on tests/unit/steps/test_steps.py
> +    assert step_1 != 1
Trying only if `return NotImplemented` is working fine if `not isinstance(other, UpgradeStep)`.

2023-10-18 17:39 UTC, rgildein commented on tests/unit/steps/test_steps.py
> +    # warnings.filterwarnings("ignore", message="coroutine '.*' was never awaited")
Yes again, thanks.

2023-10-18 17:45 UTC, rgildein commented
> I personally had a bad time trying to understand what is the `_task` introduced in the UpgradeStep and I wish it had more explanation for future maintainability.

Do you have any suggestion?
The main reason is that instead awaiting the `core` we create task which can be canceled later + we are defining name of for task so we can have watcher later checking if task is still running or something like that.

2023-10-18 21:22 UTC, agileshaw requested changes
Just two small suggestions inline. Overall I like the new approach and am looking forward to seeing everything comes together.

2023-10-18 21:22 UTC, agileshaw commented on cou/steps/__init__.py
> +        :raises CanceledUpgradeStep: If step has already been cancelled.
```suggestion
        :raises CanceledUpgradeStep: If step has already been canceled.
```

2023-10-19 12:59 UTC, gabrielcocenza approved these changes

2023-10-19 13:03 UTC, agileshaw approved these changes
LGTM

2023-10-19 19:40 UTC, agileshaw approved these changes

2023-10-19 20:18 UTC, gabrielcocenza approved these changes

2023-10-19 20:19 UTC, merged