Channel Based Class to support gnocchi, designate-bind and glance-simplestreams
canonical/charmed-openstack-upgrader pull request #156
Opened 2023-10-30 21:00 UTC by gabrielcocenza

- removed is_os_channel_based from base class

Closes: #94, #106, #125

2023-10-31 14:34 UTC, rgildein approved these changes
LGTM

2023-10-31 16:54 UTC, agileshaw requested changes
Overall LGTM. Just a few small changes required inline

2023-10-31 16:54 UTC, agileshaw commented on cou/apps/channel_based.py
> +        if self.is_versionless:
Can we include this check in the docstring?

2023-10-31 16:54 UTC, agileshaw commented on cou/apps/base.py
> +        # case we check if the attribute is already set.
```suggestion
        # NOTE(gabrielcocenza) Some applications current_os_release points
        # to channel_codename without setting the channel before. In that
        # case we set the attribute before accessing it.
```

2023-10-31 22:34 UTC, agileshaw approved these changes
LGTM, thanks

2023-11-01 09:37 UTC, rgildein approved these changes
LGTM

2023-11-01 12:40 UTC, merged