Change suffix of upgrade steps functions from plan to step
canonical/charmed-openstack-upgrader pull request #233
Opened 2024-02-05 17:36 UTC by gabrielcocenza

- removed unnecessary parallel parameter.

2024-02-05 18:38 UTC, agileshaw requested changes

2024-02-05 18:38 UTC, agileshaw commented on cou/apps/auxiliary.py
> +        """Get the ste to set correct value for require-osd-release option on ceph-mon.
```suggestion
        """Get the step to set correct value for require-osd-release option on ceph-mon.
```

2024-02-05 18:38 UTC, agileshaw commented on cou/apps/base.py
>          """Get Plan for upgrading software packages to the latest of the current release.
```suggestion
        """Get step for upgrading software packages to the latest of the current release.
```

2024-02-05 18:38 UTC, agileshaw commented on cou/apps/base.py
>          """Get plan for refreshing the current channel.
```suggestion
        """Get step for refreshing the current channel.
```

2024-02-05 18:38 UTC, agileshaw commented on cou/apps/base.py
> +    def upgrade_plan_steps(self, target: OpenStackRelease) -> list[UpgradeStep]:
```suggestion
    def upgrade_steps(self, target: OpenStackRelease) -> list[UpgradeStep]:
```

2024-02-05 18:38 UTC, agileshaw commented on cou/apps/base.py
>          """Get plan for refreshing the current channel.
And there are other similar functions require this change

2024-02-05 18:38 UTC, agileshaw commented on cou/apps/channel_based.py
>          """Post Upgrade planning.
```suggestion
        """Post Upgrade steps planning.
```

2024-02-05 18:38 UTC, agileshaw commented on cou/apps/subordinate.py
> +    def upgrade_plan_steps(self, target: OpenStackRelease) -> list[UpgradeStep]:
```suggestion
    def upgrade_steps(self, target: OpenStackRelease) -> list[UpgradeStep]:
```

2024-02-06 09:43 UTC, rgildein requested changes
This should against main branch and not dev branch, we will merge main to dev, but we want to minimize lines for review for merger of dev/data-plane to main.

2024-02-06 12:58 UTC, gabrielcocenza commented
It was asked to land those changes on main. The #235 was opened to this.

2024-02-06 12:58 UTC, closed without merging