Skip to add an empty step
canonical/charmed-openstack-upgrader pull request #260
Opened 2024-02-27 11:06 UTC by rgildein

We do not need to have empty step in plan, so I added the if condition to BaseStep.add step function to skip any empty step.

2024-02-27 18:25 UTC, agileshaw approved these changes
LGTM

2024-02-28 01:51 UTC, aieri requested changes
Nice and simple, +1... except for a function name typo, sorry ;)

2024-02-28 01:51 UTC, aieri commented on tests/unit/steps/test_steps.py
> +def test_step_add_step_skiiping_empty():
```suggestion
def test_step_add_step_skipping_empty():
```

2024-02-28 12:49 UTC, gabrielcocenza requested changes
Small change necessary, otherwise LGTM

2024-02-28 13:14 UTC, gabrielcocenza approved these changes

2024-02-28 14:46 UTC, agileshaw approved these changes

2024-02-29 03:00 UTC, aieri approved these changes

2024-02-29 14:39 UTC, merged