Bash completion for upgrade-groups
canonical/charmed-openstack-upgrader pull request #268
Opened 2024-02-29 19:28 UTC by gabrielcocenza

- added bash completion for data-plane, control-plane and hypervisors
- added --machine and --availability-zone for hypervisors
- removed supressed help messages

2024-02-29 20:37 UTC, agileshaw requested changes
Some issues with the bash completion. Here are my test results:
```
# upgrade child command should not show up after control-plane is specified
ubuntu@machine:~/sunbeam-charms$ cou plan control-plane 
--backup       --help         --model        --no-backup    --quiet        --verbose      control-plane  data-plane     hypervisors

# upgrade child command should not show up after data-plane is specified
ubuntu@machine:~/sunbeam-charms$ cou plan control-plane 
--backup       --help         --model        --no-backup    --quiet        --verbose      control-plane  data-plane     hypervisors

# Ideally should also show common args like `--help`, `--quiet`, etc
ubuntu@machine:~/sunbeam-charms$ cou plan hypervisors --
--availability-zone  --machine            
```

Feel free to refer to the code I shared in https://github.com/canonical/charmed-openstack-upgrader/issues/63 (not up to date and may not be perfect, but hopefully would help you with your approach)

2024-02-29 20:37 UTC, agileshaw commented on completions/bash/cou_bash_completion
> +            child_commands=""
This mean you will not see common options such as `--help`, `--verbose` showing for `hypervisors`, which it's not correct.

2024-02-29 20:37 UTC, agileshaw commented on completions/bash/cou_bash_completion
> +            opts="--help --quiet --verbose --model --backup --no-backup control-plane data-plane hypervisors"
`control-plane data-plane hypervisors` should belong to `child_command`

2024-02-29 20:37 UTC, agileshaw commented on completions/bash/cou_bash_completion
> +            opts="--help --quiet --verbose --model ---auto-approve --backup --no-backup control-plane data-plane hypervisors"
Same here.

2024-02-29 20:37 UTC, agileshaw commented on completions/bash/cou_bash_completion
> +    esac
We need to also add targets for `control-plane` and `data-plane` sub-commands because they still need to should some common opts.

2024-02-29 22:58 UTC, agileshaw approved these changes
LGTM

2024-03-01 11:38 UTC, rgildein approved these changes
LGTM

2024-03-01 11:47 UTC, merged