Add dependent option to BaseStep
canonical/charmed-openstack-upgrader pull request #296
Opened 2024-03-12 15:08 UTC by rgildein

This option will be used later for data-plane upgrade, where we do unit by unit.

2024-03-13 21:36 UTC, gabrielcocenza approved these changes
LGTM

2024-03-13 22:32 UTC, aieri approved these changes

2024-03-13 22:38 UTC, agileshaw requested changes
One minor wording change needed, otherwise looks good

2024-03-13 22:38 UTC, agileshaw commented on cou/steps/__init__.py
> +        :param dependent: Whether the step is dependent from other step.
```suggestion
        :param dependent: Whether the step is dependent on another step.
```

2024-03-14 13:21 UTC, agileshaw approved these changes

2024-03-15 12:41 UTC, gabrielcocenza approved these changes

2024-03-15 15:16 UTC, merged