Update documentation to align with the current implementation
canonical/charmed-openstack-upgrader pull request #363
Opened 2024-04-05 23:44 UTC by agileshaw

This patch updates the documentation to reflect the latest implementation and fixes wording issues.

2024-04-06 00:22 UTC, aieri requested changes
A few small tweaks

2024-04-06 00:22 UTC, aieri commented on docs/explanation/analysis.rst
> +and data-plane components
```suggestion
and data-plane components.
```

2024-04-06 00:22 UTC, aieri commented on docs/explanation/planning.rst
> +The **pre-upgrades** steps prepare COU for the upgrade process, which includes
```suggestion
The **pre-upgrade** steps prepare COU for the upgrade process, which includes
```

2024-04-06 00:22 UTC, aieri commented on docs/explanation/planning.rst
> +verifying the states or configurations of the applications, units, or the
```suggestion
verifying the states or configurations of the applications, units, or of the
```

2024-04-06 00:22 UTC, aieri commented on docs/explanation/planning.rst
>  The **post-upgrade** steps are responsible for making sure that upgrade finishes
```suggestion
The **post-upgrade** steps are responsible for making sure that the upgrade finishes
```

2024-04-06 00:22 UTC, aieri commented on docs/explanation/planning.rst
>  The plan can also be obtained without the need to perform cloud upgrade using
```suggestion
The plan can also be obtained without the need to perform a cloud upgrade using
```

2024-04-06 00:22 UTC, aieri commented on docs/how-to/upgrade-cloud.rst
> +continue executing each planned step. This option allows **COU** to be used by scripts
```suggestion
continues executing each planned step. This option allows **COU** to be used by scripts
```

2024-04-06 00:22 UTC, aieri commented on docs/reference/environment-variables.rst
> +  connection to the Juju model retry attempts. The default value is 2 seconds.
```suggestion
* **COU_MODEL_RETRY_BACKOFF** - defines by how many seconds the wait between
  juju model connection retry attempts will be increased every time an attempt fails. The default value is 2 seconds.
```

2024-04-08 11:37 UTC, rgildein requested changes

2024-04-08 11:37 UTC, rgildein commented on docs/explanation/planning.rst
>      Top-level plan
Should this be changed to `Upgrade cloud from '{analysis_result.current_cloud_os_release}' to '{target}'`

2024-04-08 11:37 UTC, rgildein commented on docs/explanation/planning.rst
> +    │   ├── Verify cloud is in idle state
Since we are using `├──` for dependent steps, I think we should remove these characters from all these examples. Also pipes.

2024-04-08 18:53 UTC, gabrielcocenza commented on docs/explanation/planning.rst
> +The **pre-upgrade** steps prepare COU for the upgrade process, which includes
Suggestion:
- add a paragraph saying that it's also plan for individual upgrade-groups (control-plane, data-plane and hypervisors) that are a subset of the plan above, and point to the `upgrade_group` section

2024-04-08 21:54 UTC, gabrielcocenza approved these changes
LGTM

2024-04-09 07:34 UTC, rgildein approved these changes

2024-04-09 16:25 UTC, aieri approved these changes

2024-04-09 17:28 UTC, merged