Add `CONTRIBUTING.md`
canonical/charmed-openstack-upgrader pull request #366
Opened 2024-04-09 14:31 UTC by agileshaw

This patch adds a contribution guide to provide information on how to become a contributor and how code changes should be submitted.

fixes: #211

2024-04-09 14:37 UTC, rgildein approved these changes
LGTM

2024-04-09 16:23 UTC, aieri requested changes
Thank you, this looks good! I have requested a few minor tweaks.

2024-04-09 16:23 UTC, aieri commented on CONTRIBUTING.md
> +Thank you for your interest in helping us with improving **COU**! We're open to
```suggestion
Thank you for your interest in helping us improve **COU**! We're open to
```

2024-04-09 16:23 UTC, aieri commented on CONTRIBUTING.md
> +- of the changes made
```suggestion
  of the changes made
```

2024-04-09 16:23 UTC, aieri commented on CONTRIBUTING.md
> +Once you decided which issue to work on, you can express your interest by posting
```suggestion
Once you have decided which issue to work on, you can express your interest by posting
```

2024-04-09 19:40 UTC, gabrielcocenza approved these changes

2024-04-10 08:28 UTC, rgildein approved these changes

2024-04-10 16:03 UTC, aieri approved these changes

2024-04-10 16:04 UTC, merged