Ignore waiting for machine to create Applications class
canonical/charmed-openstack-upgrader pull request #373
Opened 2024-04-11 22:32 UTC by gabrielcocenza

- if the model has an app waiting machine, the machine doesn't exist yet and COU fails with AttributeError

E.g:

```
ubuntu@fce:~$ juju status tempest
Model      Controller        Cloud/Region  Version  SLA          Timestamp
openstack  foundations-maas  maas_cloud    2.9.49   unsupported  21:20:04Z

App      Version  Status   Scale  Charm   Channel  Rev  Exposed  Message
tempest  22.04    waiting    1/2  ubuntu  stable    24  no       waiting for machine

Unit        Workload  Agent       Machine  Public address  Ports  Message
tempest/1   waiting   allocating                                  waiting for machine
tempest/3*  active    idle        7/lxd/1  10.17.2.198            

Machine  State    Address      Inst id              Series  AZ     Message
7        started  10.17.2.173  pc6a-rb3-n2          focal   zone2  Deployed
7/lxd/1  started  10.17.2.198  juju-e3e648-7-lxd-1  jammy   zone2  Container started
```

breaks with the message: `AttributeError: 'NoneType' object has no attribute 'id'`

2024-04-11 22:46 UTC, aieri requested changes
This looks good, but could you please add a unit test?

2024-04-12 10:40 UTC, rgildein requested changes

2024-04-12 10:40 UTC, rgildein commented on cou/utils/juju_utils.py
> +            if status.status.info != "waiting for machine"
Like this we will skip whole app and I do not think it's necessary, since only single unit can wait for machine.

2024-04-12 15:51 UTC, agileshaw reviewed
Good catch :+1: I have a question: is generating plan for such an application still possible? I'm especially concerned about hypervisors since we are iterating through units.

2024-05-17 06:54 UTC, closed without merging