Point to known-issues if COU execution fails
canonical/charmed-openstack-upgrader pull request #383
Opened 2024-04-22 14:33 UTC by gabrielcocenza

- added manila-ganesha workaround

2024-04-22 19:11 UTC, aieri requested changes
a minor suggestion

2024-04-22 19:11 UTC, aieri commented on docs/reference/known-issues.rst
> +In that case ,refresh the current channel of the charm to receive the fix and then run COU again.
I think the link to the bug should be made more prominent
```suggestion
Certain versions of the manila-ganesha charm incorrectly report their workload version, which can lead to false positive COU errors resembling the following one:

.. code:: bash

    [WARNING] Not possible to find the charm manila-ganesha in the lookup
    [ERROR] 'manila-ganesha' with workload version 17.1.0 has no compatible OpenStack release.

See `bug 2060751`_ for details.

If affected, refresh the manila-ganesha charm to its most recent version (within the same channel) and re-run COU.
```

2024-04-22 19:11 UTC, aieri commented on docs/reference/known-issues.rst
> +.. _manila-ganesha: https://bugs.launchpad.net/charm-manila-ganesha/+bug/2060751
```suggestion
.. _bug 2060751: https://bugs.launchpad.net/charm-manila-ganesha/+bug/2060751
```

2024-04-23 08:10 UTC, rgildein requested changes

2024-04-23 08:10 UTC, rgildein commented on cou/cli.py
> +            )
This will be print even if `Exception` happened or KeyboardInterrupt, which does not look good to me. Can we move it only for COUException?

2024-04-24 03:25 UTC, aieri approved these changes

2024-04-24 11:09 UTC, rgildein approved these changes

2024-04-24 12:19 UTC, merged