Add support for Juju 3.4
canonical/charmed-openstack-upgrader pull request #410
Opened 2024-05-13 15:08 UTC by rgildein

Fix getting results from `run_on_unit` and `run_action`. Also, series was replaced with base in juju status, so the small function to convert base to series was required.

2024-05-22 00:54 UTC, jneo8 approved these changes

2024-05-22 02:42 UTC, chanchiwai-ray approved these changes

2024-05-23 02:34 UTC, chanchiwai-ray requested changes
Can you make this change independent of snap release

2024-05-23 02:34 UTC, chanchiwai-ray commented on .github/workflows/release.yaml
Can you remove this change from this PR since you are already doing that in https://github.com/canonical/charmed-openstack-upgrader/pull/411

2024-05-23 06:09 UTC, rgildein commented on .github/workflows/release.yaml
No, because if this is merged it will be released to the edge and when we merge #411 first there is no need to remove anything.

2024-05-23 06:26 UTC, chanchiwai-ray commented on .github/workflows/release.yaml
but if you remove `*.x` in the release.yaml, it won't release to edge

2024-05-27 07:25 UTC, jneo8 requested changes
Need to fix lint.

2024-05-27 07:34 UTC, rgildein commented
> Need to fix lint.

It is not related with this PR.

2024-05-27 08:35 UTC, jneo8 approved these changes
LGTM.

Wait for #417 merged.

2024-05-28 03:30 UTC, jneo8 commented
Hi @rgildein, can you update your PR? We just fix the linter issue.

2024-05-28 06:11 UTC, chanchiwai-ray approved these changes

2024-05-28 06:22 UTC, merged