Re-add the comment about juju max frame size
canonical/charmed-openstack-upgrader pull request #454
Opened 2024-06-26 07:38 UTC by samuelallan72

This comment gives context to why a custom frame size is used. It seems to have been lost during a refactor,
so lets add it back.

2024-06-26 09:15 UTC, jneo8 requested changes
Can this be a cli argument?

2024-06-26 14:18 UTC, rgildein commented
> Can this be a cli argument?

I do not think that cli arg is good idea, but maybe we can do environment argument.

2024-06-27 03:40 UTC, chanchiwai-ray reviewed
Why are we discussing this as a cli argument? Isn't this about re-adding comment?

2024-06-27 03:40 UTC, chanchiwai-ray commented on cou/utils/juju_utils.py
>  JUJU_MAX_FRAME_SIZE: int = 2**30
What is the unit of `JUJU_MAX_FRAME_SIZE` and how is it related to the comment you add back?

2024-06-27 09:41 UTC, jneo8 submitted a review, later dismissed

2024-06-27 09:52 UTC, chanchiwai-ray commented on cou/utils/juju_utils.py
>  JUJU_MAX_FRAME_SIZE: int = 2**30
Free feel to resolve it when you have or don't have the answer 🙂 but we should keep the comment correct

2024-06-27 09:56 UTC, chanchiwai-ray commented on cou/utils/juju_utils.py
>  JUJU_MAX_FRAME_SIZE: int = 2**30
If the source code is correct: https://github.com/juju/python-libjuju/blob/master/juju/client/connection.py#L231-L242, then the unit should be `byte`

2024-06-28 02:07 UTC, chanchiwai-ray approved these changes

2024-07-01 13:35 UTC, gabrielcocenza approved these changes

2024-07-01 22:01 UTC, merged