VersionRange raise ValueError if upper is not bigger than lower.
canonical/charmed-openstack-upgrader pull request #46
Opened 2023-09-05 21:30 UTC by gabrielcocenza

Closes #37

2023-09-05 21:47 UTC, agileshaw requested changes
Overall LGTM, just some wording changes suggested inline

2023-09-05 21:47 UTC, agileshaw commented on cou/utils/openstack.py
> +            raise ValueError("Upper version it is not bigger than lower version.")
```suggestion
            raise ValueError("The upper bound version is not higher than the lower bound version.")
```

2023-09-05 21:47 UTC, agileshaw commented on cou/utils/openstack.py
> +        """Initialize the VersionRange dataclass and check values."""
```suggestion
        """Initialize the VersionRange dataclass and check its values."""
```

2023-09-05 21:55 UTC, gabrielcocenza commented on cou/utils/openstack.py
> +            raise ValueError("Upper version it is not bigger than lower version.")
Done

2023-09-05 21:55 UTC, gabrielcocenza commented on cou/utils/openstack.py
> +        """Initialize the VersionRange dataclass and check values."""
Done

2023-09-05 21:56 UTC, agileshaw approved these changes
+1 from me. Thanks :)

2023-09-06 12:33 UTC, esunar approved these changes

2023-09-06 12:35 UTC, merged