Add benefit sentence for archive + purge
canonical/charmed-openstack-upgrader pull request #592
Opened 2024-10-21 07:01 UTC by chanchiwai-ray

2024-10-21 13:02 UTC, gabrielcocenza approved these changes

2024-10-21 22:19 UTC, samuelallan72 requested changes
I was hoping for this to include more information as a reference or deeper explanation. We already say elsewhere the high level things (optimise upgrade, reduce db size, improve performance), but it would be good to add some practical technical details.

Especially important is an explanation of how the db will have unbounded growth, unless the soft deleted data is archived (moved to another table) and then purged (deleted).

2024-10-22 01:29 UTC, chanchiwai-ray commented
> ...some practical technical details. Especially important is an explanation of how the db will have unbounded growth, unless the soft deleted data is archived (moved to another table) and then purged (deleted).

I am not familiar with this topic though, and I am not convinced that would be useful for the user. Do you have any reference for that topic? Maybe a viable option is to include the technical detail as a reference link

2024-10-22 03:02 UTC, samuelallan72 commented
> I am not familiar with this topic though, and I am not convinced that would be useful for the user. Do you have any reference for that topic? 

I can take a look sometime to go through previous threads and gather materials. This information is useful to the user if we present it well - the user may ask why do we need these? what is the purpose? why does it improve performance? why does it save disk space? etc.

2024-10-22 03:14 UTC, jneo8 submitted a review, later dismissed

2024-10-22 06:01 UTC, samuelallan72 requested changes
Thanks for finding this information @chanchiwai-ray! I've left some suggestions to consider. :)

2024-10-22 06:01 UTC, samuelallan72 commented on docs/explanation/nova-data-migration.rst
> +This command will remove the entries in the shadow table.
Maybe add here something like: this can free up disk space.

2024-10-22 06:01 UTC, samuelallan72 commented on docs/explanation/nova-data-migration.rst
> +When an instance is deleted, an entry will still be kept in the active table but marked as **deleted**. This command will move those entries from the active table to the shadow table.
(The idea is to add a "why" to this section and the next)

2024-10-22 21:54 UTC, samuelallan72 approved these changes

2024-10-23 06:04 UTC, Pjack approved these changes

2024-10-23 06:28 UTC, merged