Accept more than one possible current channel for auxiliary charms
canonical/charmed-openstack-upgrader pull request #77
Opened 2023-09-21 22:24 UTC by gabrielcocenza

- rabbitmq and hacluster can have more than one compatible channel
  for a range of OpenStack releases.

2023-09-22 21:26 UTC, agileshaw requested changes

2023-09-22 21:26 UTC, agileshaw commented on cou/apps/app.py
> -        )
A default description is still needed at L#514 for charmhub aoplication with channel outside of the possible_current_channels list.

2023-09-22 21:26 UTC, agileshaw commented on cou/apps/app.py
> -        )
Also, could you add a unit test for this case?

2023-09-26 20:54 UTC, agileshaw approved these changes
LGTM

2023-09-29 12:36 UTC, rgildein approved these changes
LGTM

2023-09-29 12:53 UTC, agileshaw approved these changes

2023-09-29 13:35 UTC, merged